"""
report_generator.py
--------------------
Takes the aggregated results from all agents and produces:
  1. A structured Markdown report
  2. A PDF version of the same report

Output format matches the assignment's Evaluation Report requirements:
  - Executive Summary (Pass/Fail)
  - Consistency Score (0-100)
  - Grammar Rating (High/Medium/Low)
  - Novelty Index (qualitative)
  - Fact Check Log
  - Accuracy/Fabrication Score
"""

import os
import re
from datetime import datetime
from fpdf import FPDF


OUTPUT_DIR = os.getenv("REPORT_OUTPUT_DIR", "./reports")


# ── Markdown report ───────────────────────────────────────────────────────────

def generate_markdown_report(evaluation: dict) -> str:
    """
    Generate a comprehensive Markdown report from evaluation results.
    Returns the Markdown string.
    """
    meta    = evaluation["paper_meta"]
    scores  = evaluation["scores"]
    results = evaluation["results"]
    stats   = evaluation["section_stats"]

    title       = meta.get("title", "Unknown Paper")
    authors     = meta.get("authors", "Unknown")
    arxiv_id    = meta.get("arxiv_id", "")
    scrape_src  = meta.get("source", "unknown")
    now         = datetime.now().strftime("%Y-%m-%d %H:%M UTC")

    verdict     = scores.get("overall_verdict", "UNKNOWN")
    c_score     = scores.get("consistency_score", "N/A")
    g_rating    = scores.get("grammar_rating", "N/A")
    n_index     = scores.get("novelty_index", "N/A")
    fab_prob    = scores.get("fabrication_probability", "N/A")
    fc_summary  = scores.get("fact_check_summary", {})

    verdict_emoji = {"PASS": "✅", "CONDITIONAL PASS": "⚠️", "FAIL": "❌"}.get(verdict, "❓")

    md = f"""# Judgement Report — Agentic Research Paper Evaluator

---

## Paper Information

| Field      | Value |
|------------|-------|
| **Title**  | {title} |
| **Authors**| {authors} |
| **arXiv**  | https://arxiv.org/abs/{arxiv_id} |
| **Source** | {scrape_src} |
| **Report Generated** | {now} |

---

## Executive Summary

### {verdict_emoji} Overall Verdict: {verdict}

| Metric | Score |
|--------|-------|
| Consistency Score | {c_score}/100 |
| Grammar Rating | {g_rating} |
| Novelty Index | {n_index} |
| Fabrication Probability | {fab_prob}% |
| Facts Verified | {fc_summary.get('verified_count', 'N/A')} |
| Facts Contradicted | {fc_summary.get('contradicted_count', 'N/A')} |

---

## Section 1 — Consistency Analysis

**Score: {c_score}/100**

{_clean_agent_output(results.get('consistency', 'No output generated.'))}

---

## Section 2 — Grammar & Language Analysis

**Rating: {g_rating}**

{_clean_agent_output(results.get('grammar', 'No output generated.'))}

---

## Section 3 — Novelty Assessment

**Novelty Index: {n_index}**

{_clean_agent_output(results.get('novelty', 'No output generated.'))}

---

## Section 4 — Fact Check Log

**Verified: {fc_summary.get('verified_count', '?')} | Unverified: {fc_summary.get('unverified_count', '?')} | Contradicted: {fc_summary.get('contradicted_count', '?')} | Suspicious: {fc_summary.get('suspicious_count', '?')}**

{_clean_agent_output(results.get('factcheck', 'No output generated.'))}

---

## Section 5 — Authenticity & Fabrication Risk

**Fabrication Probability: {fab_prob}%**

{_clean_agent_output(results.get('authenticity', 'No output generated.'))}

---

## Paper Structure Statistics

| Section | Characters | Tokens |
|---------|-----------|--------|
"""
    for section, stat in stats.items():
        md += f"| {section.replace('_', ' ').title()} | {stat['chars']:,} | {stat['tokens']:,} |\n"
    md += f"\n---\n\n"
    md += f"*Report generated by Agentic Research Paper Evaluator*  \n"
    md += f"*Powered by CrewAI + Gemini 1.5 Flash*\n"

    return md


def _clean_agent_output(text: str) -> str:
    # Remove score/rating lines already shown in section headers
    score_tags = [
        r'CONSISTENCY_SCORE:\s*\d+\s*\n?',
        r'GRAMMAR_RATING:\s*\S+\s*\n?',
        r'NOVELTY_INDEX:\s*\S+\s*\n?',
        r'FABRICATION_PROBABILITY:\s*[\d\.]+%?\s*\n?',
        r'REPRODUCIBILITY_SCORE:\s*\S+\s*\n?',
        r'VERIFIED_COUNT:\s*\d+\s*\n?',
        r'UNVERIFIED_COUNT:\s*\d+\s*\n?',
        r'CONTRADICTED_COUNT:\s*\d+\s*\n?',
        r'_?CHECK_LOG:\s*\n?',
        r'FACT_CHECK_LOG:\s*\n?',
        r'Unkey Findings',
        r'_INDEX:\s*\S+\s*\n?',        
        r'SUSPICIOUS_COUNT:\s*\d+\s*\n?',
    ]
    for pattern in score_tags:
        text = re.sub(pattern, '', text, flags=re.IGNORECASE)

    # Convert ALL_CAPS_TAGS: → ### Heading
    def tag_to_heading(m):
        tag = m.group(1).replace('_', ' ').title()
        return f'\n### {tag}\n'
    text = re.sub(r'(?m)^([A-Z][A-Z_]{2,}):\s*$', tag_to_heading, text)
    text = text.replace('Unkey Findings', 'Key Findings')
    # Normalise bullet styles
    text = re.sub(r'(?m)^\*\s+', '- ', text)
    text = re.sub(r'(?m)^•\s+', '- ', text)

    # Clean up excessive blank lines
    text = re.sub(r'\n{3,}', '\n\n', text)

    return text.strip()

def _make_title_slug(evaluation: dict) -> str:
    """Convert paper title to a clean filename slug."""
    title = evaluation["paper_meta"].get("title", "unknown_paper")
    # Keep only alphanumeric and spaces, then replace spaces with underscores
    slug = re.sub(r'[^\w\s]', '', title)        # remove punctuation
    slug = re.sub(r'\s+', '_', slug.strip())    # spaces → underscores
    slug = slug[:60]                             # cap at 60 chars
    return slug

# ── Save Markdown ─────────────────────────────────────────────────────────────

def save_markdown_report(evaluation: dict) -> str:
    """Save Markdown report to disk. Returns file path."""
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    arxiv_id  = evaluation["paper_meta"].get("arxiv_id", "unknown").replace("/", "_")
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"{_make_title_slug(evaluation)}_evaluation_report.md"
    filepath  = os.path.join(OUTPUT_DIR, filename)

    md_content = generate_markdown_report(evaluation)
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(md_content)

    print(f"[Report] Markdown saved: {filepath}")
    return filepath


# ── PDF report ────────────────────────────────────────────────────────────────

class PaperReportPDF(FPDF):
    """Custom PDF class with header/footer."""

    def __init__(self, title="Judgement Report"):
        super().__init__()
        self.report_title = title
        self.set_margins(20, 20, 20)
        self.set_auto_page_break(auto=True, margin=20)

    def header(self):
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(100, 100, 100)
        self.cell(0, 8, "Agentic Research Paper Evaluator - Judgement Report", align="L")
        self.ln(4)
        self.set_draw_color(200, 200, 200)
        self.line(20, self.get_y(), 190, self.get_y())
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 8, f"Page {self.page_no()} - Generated {datetime.now().strftime('%Y-%m-%d')}", align="C")

    def add_section_title(self, text: str):
        self.set_font("Helvetica", "B", 13)
        self.set_text_color(30, 30, 30)
        self.ln(6)
        self.cell(0, 8, text, ln=True)
        self.set_draw_color(80, 80, 200)
        self.line(20, self.get_y(), 190, self.get_y())
        self.ln(4)

    def add_score_badge(self, label: str, value: str, color: tuple = (50, 120, 200)):
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(*color)
        self.cell(0, 7, f"{label}: {value}", ln=True)
        self.set_text_color(30, 30, 30)

    def add_body_text(self, text: str, font_size: int = 10):
        self.set_font("Helvetica", size=font_size)
        self.set_text_color(40, 40, 40)
        # Encode to latin-1 safe
        safe_text = text.encode("latin-1", errors="replace").decode("latin-1")
        self.multi_cell(0, 6, safe_text)
        self.ln(2)

    def add_verdict_box(self, verdict: str, scores: dict):
        """Draw a summary box with all scores."""
        verdict_colors = {
            "PASS":             (0, 160, 80),
            "CONDITIONAL PASS": (200, 140, 0),
            "FAIL":             (200, 50, 50),
        }
        color = verdict_colors.get(verdict, (100, 100, 100))

        self.set_fill_color(*color)
        self.set_text_color(255, 255, 255)
        self.set_font("Helvetica", "B", 14)
        self.cell(0, 12, f"  Overall Verdict: {verdict}", fill=True, ln=True)
        self.ln(4)

        self.set_text_color(30, 30, 30)
        self.set_font("Helvetica", "B", 10)

        score_lines = [
            ("Consistency Score",      f"{scores.get('consistency_score', 'N/A')}/100"),
            ("Grammar Rating",         str(scores.get("grammar_rating", "N/A"))),
            ("Novelty Index",          str(scores.get("novelty_index", "N/A"))),
            ("Fabrication Risk",       f"{scores.get('fabrication_probability', 'N/A')}%"),
        ]
        for label, value in score_lines:
            self.set_font("Helvetica", "B", 10)
            self.cell(70, 7, label + ":")
            self.set_font("Helvetica", size=10)
            self.cell(0, 7, value, ln=True)
        self.ln(4)


def generate_pdf_report(evaluation: dict) -> str:
    """
    Generate PDF report and save to disk. Returns file path.
    """
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    arxiv_id  = evaluation["paper_meta"].get("arxiv_id", "unknown").replace("/", "_")
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"{_make_title_slug(evaluation)}_evaluation_report.pdf"
    filepath  = os.path.join(OUTPUT_DIR, filename)

    meta    = evaluation["paper_meta"]
    scores  = evaluation["scores"]
    results = evaluation["results"]

    pdf = PaperReportPDF()
    pdf.add_page()

    # ── Cover / header ───────────────────────────────
    pdf.set_font("Helvetica", "B", 16)
    pdf.set_text_color(20, 20, 80)
    pdf.multi_cell(0, 10, f"Judgement Report\n{meta.get('title', 'Unknown')}")
    pdf.ln(2)

    pdf.set_font("Helvetica", size=10)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(0, 6, f"Authors: {meta.get('authors', 'Unknown')}", ln=True)
    pdf.cell(0, 6, f"arXiv: https://arxiv.org/abs/{meta.get('arxiv_id', '')}", ln=True)
    pdf.cell(0, 6, f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M UTC')}", ln=True)
    pdf.ln(6)

    # ── Executive summary ─────────────────────────────
    pdf.add_section_title("Executive Summary")
    pdf.add_verdict_box(scores.get("overall_verdict", "UNKNOWN"), scores)

    # ── Section outputs ───────────────────────────────
    sections_to_render = [
        ("1. Consistency Analysis",          "consistency",  f"Score: {scores.get('consistency_score', 'N/A')}/100"),
        ("2. Grammar & Language Analysis",   "grammar",      f"Rating: {scores.get('grammar_rating', 'N/A')}"),
        ("3. Novelty Assessment",            "novelty",      f"Index: {scores.get('novelty_index', 'N/A')}"),
        ("4. Fact Check Log",                "factcheck",    ""),
        ("5. Authenticity & Fabrication Risk","authenticity", f"Risk: {scores.get('fabrication_probability', 'N/A')}%"),
    ]

    for section_title, key, subtitle in sections_to_render:
        pdf.add_page()
        pdf.add_section_title(section_title)
        if subtitle:
            pdf.add_score_badge("", subtitle)
        content = results.get(key, "No output generated.")
        pdf.add_body_text(_clean_agent_output(content))

    pdf.output(filepath)
    print(f"[Report] PDF saved: {filepath}")
    return filepath


# ── Convenience function ──────────────────────────────────────────────────────

def generate_all_reports(evaluation: dict) -> dict:
    """Generate both Markdown and PDF reports. Returns dict of file paths."""
    return {
        "markdown": save_markdown_report(evaluation),
        "pdf":      generate_pdf_report(evaluation),
    }